# Generated by Django 3.2.16 on 2024-09-28 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Kategoriya')),
                ('slug', models.SlugField(unique=True, verbose_name='Identifikator')),
            ],
            options={
                'verbose_name': 'kategoriya',
                'verbose_name_plural': 'kategoriyalar',
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Lavha')),
                ('text', models.TextField(verbose_name='Tekst')),
                ('image', models.ImageField(blank=True, null=True, upload_to='rasmlar/', verbose_name='Rasm')),
                ('pub_date', models.DateTimeField(help_text="Agar kelajakda sanani va vaqtni o‘rnatmoqchi bo‘lsangiz — kechiktirilgan e'lonlar qilish mumkin.", verbose_name="E'lon qilish sanasi va vaqti")),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='pages.category', verbose_name='Katagoriya')),
            ],
            options={
                'verbose_name': "e'lon",
                'verbose_name_plural': "e'lonlar",
                'ordering': ('-pub_date',),
            },
        ),
    ]
