# Generated by Django 3.2.16 on 2024-09-28 08:31

from django.db import migrations, models
import pages.models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=pages.models.unique_image_filename, verbose_name='Rasm'),
        ),
    ]
